### ISSUE TITLE
Unable to customize directory length

### ISSUE THREAD

**Issue by rdacquisto** [zimfw/sorin#2]
I've tried to configure `zstyle ':zim:prompt-pwd:fish-style' dir-length 4`, but still see a directory length of 1. I believe this line is the root cause: https://github.com/zimfw/sorin/blob/beb3292ffa1e61451a5dd4933948f27e9436c979/sorin.zsh-theme#L53

Is there a way to override this value, while maintaining the default value of 1?

**Comment by ericbn** [comment]
Hi @rdacquisto. You need to override the zstyle by setting it after the `source ${ZIM_HOME}/init.zsh` in your .zshrc file.

**Comment by rdacquisto** [comment]
Oh thanks @ericbn. That makes a lot of sense.
